### PR TITLE
Commit from Max who created conflict

### PR DESCRIPTION
**Pull request by maximvoronov757**
this is a conflict from MAx

### CODE REVIEW

**Review by lo-guliko — APPROVED** [review]
good stuff

**Comment by lo-guliko** [comment]
good stuff

**Comment by Zgurskiy11** [comment]
good

**Comment by lo-guliko** [comment]
approval granted

**Review by Zgurskiy11 — APPROVED** [review]
all good,,, but spaghetti

**Review by MjSemati — CHANGES_REQUESTED** [review]
Max please change it

**Review by lo-guliko — CHANGES_REQUESTED** [review]
please make adjustments

**Comment by maximvoronov757** [comment]
I closing and deleting my branch((((

**Pull request closed without merging**
